image: node

pages:
  stage: deploy
  script:
  - npm update
  - npm install node-sass
  - npm run build
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
