image: node

pages:
  stage: deploy
  script:
  - npm update
  - npm install node-sass
  - npm run build
  - mkdir .public
  - mkdir .public/build
  - mv build .public/build
  - cp index.html .public
  - cp -r .public public
  artifacts:
    paths:
    - public
  only:
  - master
