image: node

pages:
  stage: deploy
  script:
  - npm update
  - npm install node-sass
  - npm run buildprod
  - mkdir .public
  - mkdir .public/build
  - cp index.html .public
  - cp howitworks.html .public
  - cp build/bundle.js .public/build
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
